### ISSUE TITLE
HelmRelease, GitRepository and applied revisions

### ISSUE THREAD

**Issue by sylr** [fluxcd/helm-controller#184]
When using a GitRepository as chart source for a HelmRelease the `spec.Chart.spec.Version` of the HelmRelease is not honoured.

This should be reflected in the Status of the HelmRelease, i.e., `Last Applied Revision` and `Last Attempted Revision` should point to the git revision of the source instead of the `Version` value of the Chart.yaml which can be outdated.

**Comment by sbernheim** [comment]
Hi, @sylr -

I realize that this is a rather old Issue, but is it still a problem for your use-case?

This seems like one of those integration points between Helm (for the Helm chart version) and the Controller/Toolkit's (for the Git revision hash) perspectives on Git-based charts that would need to be balanced against each other for the `Last Applied/Attempted Revision` values to be meaningful in-context.

Though the Chart may be originally sourced from a Git repo, Helm would still see it as a chart like any other and the version expressed in the `Chart.yaml` file is still the controlling version as far as Helm is concerned.  I don't know if other Helm Controller users would expect it to substitute in a Git revision or version tag under the circumstances.

But it does bear some thought, and the expected behavior could at least be documented.

**Comment by stefanprodan** [comment]
In Flux 2.4, setting `reconcileStrategy: Revision` appends the short Git SHA to the chart version.
