### ISSUE TITLE
Add timestamps to captured Helm logs

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/helm-controller#312]
In #219 we started capturing Helm logs, the output at present could however be improved to make it easier to distinguish lines and provide indicators about for example the time it took for a sub action to run.

Current output:

```console
Last Helm logs:

creating 8 resource(s)
beginning wait for 8 resources with timeout of 5m0s
Deployment is not ready: default/myapp-back. 0 out of 1 expected pods are ready
```

Improved example output:

```console
Last Helm logs:

[<timestamp>] creating 8 resource(s)
[<timestamp>] beginning wait for 8 resources with timeout of 5m0s
[<timestamp>] Deployment is not ready: default/myapp-back. 0 out of 1 expected pods are ready
```

**Comment by pradeepnnv** [comment]
I would like to give this a try.

**Comment by hiddeco** [comment]
@pradeepnnv all yours, if you need help, just comment here :-).

**Comment by peterfication** [comment]
I wanted to give this a try but I'm not sure in which place I would add the timestamps. I would have added them in the [`LogBuffer.Log` method](https://github.com/fluxcd/helm-controller/blob/f79900ebd745883dc760737cf88bde0c404443d6/internal/runner/log_buffer.go#L66), so that the recorded timestamps match the time they were logged. If I add them in [`wrapActionError`](https://github.com/fluxcd/helm-controller/blob/f79900ebd745883dc760737cf88bde0c404443d6/internal/runner/runner.go#L400) or [`handleHelmActionResult`](https://github.com/fluxcd/helm-controller/blob/f79900ebd745883dc760737cf88bde0c404443d6/controllers/helmrelease_controller.go#L677), all timestamps of the individual captured messages will be the same, which is not what we want here, I assume.

Or maybe I was all wrong and there is another place where it needs to be added? Any hint is appreciated :)
