### ISSUE TITLE
Review/extend DEVELOPMENT documentation

### ISSUE THREAD

**Issue by dholbach** [fluxcd/helm-controller#341]
> Each of the controllers should have clear guidelines on how to build and run the
> projects. This includes the sections:
> ○ How to install dependencies
> ○ How to install the controller
> ○ How to run the test suite locally
> ○ How to run the controller locally

Some of the information might already be there - let's double-check it's up to date and accurate.

**Comment by cebernardi** [comment]
Hi all!
I was recently trying to set up the project and run the tests (MacOS environment) and I noticed that:
- tests fail to run if one doesn't have `kubebuilder-tools` installed (`unable to start control plane itself: failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory`); I see that there is already a possibly related [open issue](https://github.com/fluxcd/helm-controller/issues/325) 
- version 0.5.0+ of `controller-gen` should be enforced (https://github.com/fluxcd/helm-controller/blob/fd79fac12c2f984012eb5954b6e2af2e2be54f8c/Makefile#L108); I had 0.4.0 and the Makefile target did not download a new version, so I run into the `controller-gen` bug where negative values are generated as strings ([here](https://github.com/kubernetes-sigs/kubebuilder/issues/1634) the bug and [here](https://github.com/fluxcd/helm-controller/blob/fd79fac12c2f984012eb5954b6e2af2e2be54f8c/api/v2beta1/helmrelease_types.go#L894) the bit that was failing for me)

I see that the new projects generated with kubeebuilder adopt a different approach and download both `controller-gen` and `test-env` into a local folder, so only the project scope is affected.

If there is consensus I could adapt the Makefile to this approach as well. 

Otherwise, I could just add some lines to the DEVELOPMENT.md where I list the above as manual steps.
