### ISSUE TITLE
Is there a FluxCD equivalent to "argocd app wait" or "helm upgrade --wait"?

### ISSUE THREAD

**Issue by qingvincentyin** [fluxcd/helm-controller#355]
I described the following problem and the steps to reproduce the problem:

- https://stackoverflow.com/questions/68462882/is-there-a-fluxcd-equivalent-to-argocd-app-wait-or-helm-upgrade-wait

Nobody has been able to answer it on the internet. This problem looks like a product bug to me.

Opinions?

**Comment by kingdonb** [comment]
There are several answers to this question now, that were not available yet when this question was first posted:

> `flux --version`
> `flux version 0.16.1`

With Helm Controller, for a long time now (longer than 0.16.1) the install was configured to run as the equivalent of `helm install --wait`. So whatever failures `helm --wait` would detect, the Helm Controller should also perceive as failures.

(That's not what is shown in the Stack Overflow post, but I have followed the steps in the post with Flux v0.22.0, the latest version as of yesterday when you posted this issue, and it seems to catch the failure as expected.)

```
(⎈ |oidc@moo:default):~/jenkins-infra (main u=)$ kubectl create ns traefik
namespace/traefik created

(⎈ |oidc@moo:default):~/jenkins-infra (main u=)$ flux create source helm traefik --url https://helm.traefik.io/traefik --namespace traefik
✚ generating HelmRepository source
► applying HelmRepository source
✔ source created
◎ waiting for HelmRepository source reconciliation
✔ HelmRepository source reconciliation completed
✔ fetched revision: e5c48d54bd65ba18ce606a6d7dd720b10a46a6bf

(⎈ |oidc@moo:default):~/jenkins-infra (main u=)$ vi values-6666.yaml

(⎈ |oidc@moo:default):~/jenkins-infra (main u=)$ flux create helmrelease my-traefik --chart traefik --source HelmRepository/traefik --chart-version 9.18.2 --namespace traefik --values=./values-6666.yaml
✚ generating HelmRelease
► applying HelmRelease
✔ HelmRelease created
◎ waiting for HelmRelease reconciliation
✔ HelmRelease my-traefik is ready
✔ applied revision 9.18.2

(⎈ |oidc@moo:default):~/jenkins-infra (main u=)$ flux get helmreleases --namespace traefik
NAME      	READY	MESSAGE                         	REVISION	SUSPENDED
my-traefik	True 	Release reconciliation succeeded	9.18.2  	False
```

This appears to be a bug. In fact I think I have seen this bug before:

```
$ k get po
NAME                          READY   STATUS    RESTARTS   AGE
my-traefik-654db6c87d-tkbrk   0/1     Running   2          100s
$ flux reconcile --namespace traefik hr my-traefik
► annotating HelmRelease my-traefik in traefik namespace
✔ HelmRelease annotated
◎ waiting for HelmRelease reconciliation
✔ applied revision 9.18.2
```

If I remember the bug correctly, it's not so much a bug as it is rigid and unyielding interpretation of config as written.

Helm considers a deployment with one replica and strategy `rollingUpdate` with `maxUnavailable` of 1 to be ready when it has 1 unavailable deployment. (Even if the deployment's one and only pod has entered CrashLoopBackOff and readiness and liveness checks have all failed... with maxUnavailable of 1 and replicas of 1, the deployment technically has no more than the allowed number of unavailable pods, so it is considered ready.)

You can confirm this is the same issue by setting replicas to 2, which I tested as well, and found that this version does indeed fail to become ready as you were hoping to see:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 10.6.1
  interval: 1m0s
  timeout: 30s
  values:
    deployment:
      replicas: 2
    ports:
      traefik:
        healthchecksPort: 6666
```

In this version I have added `timeout: 30s` which is required so you can see the failure messages from Helm in `kubectl describe helmreleases.helm.toolkit.fluxcd.io -n traefik my-traefik`

I think this is slightly regressive compared to Kustomize Controller, which shows the wait conditions that have failed regardless of whether any timeout is set. I also noticed that setting `--timeout` on `flux create helmrelease` did not do what I expected it to do, it is a global option for `flux` and there is actually no CLI flag which I can pass to add the declarative timeout to the declarative artifact. You have to write the resource as YAML, or export it and add one (for now at least.)

```
$ k apply -f helmrelease.yaml
helmrelease.helm.toolkit.fluxcd.io/my-traefik created
$ k get helmreleases.helm.toolkit.fluxcd.io
NAME         READY     STATUS                       AGE
my-traefik   Unknown   Reconciliation in progress   16s
$ k get helmreleases.helm.toolkit.fluxcd.io
NAME         READY     STATUS                       AGE
my-traefik   Unknown   Reconciliation in progress   26s
$ k get helmreleases.helm.toolkit.fluxcd.io
NAME         READY   STATUS                      AGE
my-traefik   False   install retries exhausted   35s

$ k describe helmreleases.helm.toolkit.fluxcd.io my-traefik
Name:         my-traefik
Namespace:    traefik
...
Events:
  Type    Reason  Age   From             Message
  ----    ------  ----  ----             -------
  Normal  info    45s   helm-controller  HelmChart 'traefik/traefik-my-traefik' is not ready
  Normal  info    45s   helm-controller  Helm install has started
  Normal  error   14s   helm-controller  Helm install failed: timed out waiting for the condition

Last Helm logs:

creating 1 resource(s)
CRD traefikservices.traefik.containo.us is already present. Skipping.
creating 5 resource(s)
beginning wait for 5 resources with timeout of 30s
Deployment is not ready: traefik/my-traefik. 0 out of 1 expected pods are ready
  Normal  error  14s                helm-controller  reconciliation failed: Helm install failed: timed out waiting for the condition
  Normal  error  3s (x11 over 14s)  helm-controller  reconciliation failed: install retries exhausted
```

This story is (un)fortunately much better right now in the Kustomize Controller than here in Helm Controller, where on a Kustomization you can simply set `spec.wait` as `true`, and additionally set a `spec.timeout` if desired, so that it can differ from the default value of `spec.interval - 30s`, which can be extremely desirable in case your `interval` is longer than a couple of minutes, to get fast feedback from the health checking capabilities. (But for a Kustomization that applies a HelmRelease, Kustomize health checks will still depend on the behavior from HelmRelease, that depends on Helm itself.)

In earlier versions of Kustomize Controller, it was necessary to write `healthChecks` section which enumerated all the resources to check, but this is no longer required as of Flux 0.18.0. You can just use the `wait` flag now.

Anyway, as for Helm, this appears to be the same issue reported here:
* https://github.com/helm/helm/issues/3173
and resurrected here:
* https://github.com/helm/helm/issues/10061

**Comment by qingvincentyin** [comment]
Super! Now I know how to handle it, given your explanation.
Closing the issue.

**Comment by kingdonb** [comment]
I think you can actually write an explicit health check in your Kustomization to solve this problem. If you are using a Flux Kustomization to create your HelmRelease, this might be the real best answer yet since I do consider this a Helm bug!

Since Kustomization's health check is smart enough to know that a Deployment with one replica is not ready until it has come up, even if Helm is not... but Kustomization is not smart enough to reach through a HelmRelease and check the resources that were created by it on its own.

https://github.com/kingdon-ci/jenkins-infra/tree/main/apps/traefik
and
https://github.com/kingdon-ci/jenkins-infra/tree/main/clusters/moo-cluster/traefik

From `flux-kustomization.yaml`, with `wait: false` and `replicas: 1`:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 30s
  path: ./apps/traefik
  prune: false
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: my-traefik
      namespace: traefik
```

Nothing stops you from adding `healthChecks` for resources that are not explicitly in the Kustomization, reaching through a HelmRelease to check something that you don't trust Helm to check, or even resources that are pre-existing in `kube-system` and might not have been installed or controlled by Flux in any way.

This is perhaps an abuse of power, but it is technically possible in the GitOps Toolkit API, and it might scratch the itch, in other words therefore the most straightforward way to resolve this issue directly for now, once you became aware of it:

```
$ k get hr.helm.toolkit.fluxcd.io
NAME         READY   STATUS                             AGE
my-traefik   True    Release reconciliation succeeded   5m5s

(but):

$ flux get ks traefik
NAME   	READY	MESSAGE                                                                                                                                      	REVISION	SUSPENDED
traefik	False	Health check failed after 30.013654341s, timeout waiting for: [Deployment/traefik/my-traefik status: 'InProgress': context deadline exceeded]	        	False
```

Glad this was helpful for you! Thanks for reporting the trouble.
