### ISSUE TITLE
Manually enforce reconciliation in the face of exhausted retry contingent

### ISSUE THREAD

**Issue by makkes** [fluxcd/helm-controller#366]
The [documentation](https://github.com/fluxcd/helm-controller/blob/7a570b8f7a056c7430401a9c94f62dc986e46d7c/docs/spec/v2beta1/helmreleases.md#reconciliation) says that 
> The reconciler can be told to reconcile the HelmRelease outside of the specified interval by annotating the object with a reconcile.fluxcd.io/requestedAt annotation
but that only works when the number of retries has not been exhausted, yet. Currently, the only way to enforce another reconciliation of a HelmRelease is a deletion of the resource and waiting on it getting created again from Git (or manually if no Git repo is involved).

I would like to propose changing the behaviour of the `reconcile.fluxcd.io/requestedAt` annotation to always reconcile even if the number of retries is exhausted.

**Comment by stefanprodan** [comment]
> I would like to propose changing the behaviour of the reconcile.fluxcd.io/requestedAt annotation to always reconcile even if the number of retries is exhausted.

I agree, right now only the HelmRelease Kind behaves differently.

**Comment by hiddeco** [comment]
> [..] right now only the HelmRelease Kind behaves like this, [..]

This is not true, the `requestedAt` annotation requests a reconciliation, which the controller does like all other controllers. Where the controller differs from e.g. the kustomize-controller however, is that it does not perform a blind apply (or Helm release in this case) nor endless retry, because this would cause the storage to drift.

Due to this, and because the release itself is a long running process, I think it should be a separate annotation which on the CLI side is used as a replacement for `requestedAt`, when you run `flux reconcile ... --force`. Which effectively disables the remediation strategy (and limitations) for that reconcile.

**Comment by stefanprodan** [comment]
> because this would cause the storage to drift.

Right I forgot about this, so we need a different annotation for the helm API only, that the CLI sets when `--force` is set.

**Comment by hiddeco** [comment]
The question is if the annotation only ignores the failure count of the defined remediation strategy (`remediateAt`?), or if it does more.
