### ISSUE TITLE
Unusually higher memory spikes with 0.25

### ISSUE THREAD

**Issue by palexster** [fluxcd/helm-controller#546]
We are experiencing an unusually higher memory consumption for the helm controller in the 0.25 version.

An example, testing helm-controller 0.17.2, we had the following memory consumption for 46 charts:

![00340e77-becf-45ae-98d3-36ca3ec58ee2](https://user-images.githubusercontent.com/1481739/196721110-9f0e7d27-17ec-4600-8904-965a9e0d30c6.png)

It remained lower than 500MB.
When upgrading to 0.25.0, we had the same configuration (46 HelmReleases to reconcile) but higher spikes: It goes over 600 MB in the same scenario.

![Screenshot from 2022-10-19 16-54-13](https://user-images.githubusercontent.com/1481739/196730475-9c175ce3-1e71-4b3c-b05d-ee566f6a2fc1.png)

With more HelmReleases, we observe this delta becoming more prominent. Is this behavior somehow expected with recent changes?

**Comment by pjbgf** [comment]
There is a substantial amount of [changes between those two versions](https://github.com/fluxcd/helm-controller/compare/v0.17.0...v0.25.0), including important security fixes, however, I am not aware of any changes that should incur such a performance tax.

Were both controllers targeting the _exact version_ of the helm index or were those graphs extracted from different points in time? Comparing both graphs, the latter version has a higher initial spike, but a lesser memory consumption over time (with also less variance).

If the memory peak is an issue for you, from `v0.25` you should be able to set `GOMEMLIMIT` as an environment variable, so that Go knows how much memory it should use. Use that in combination with your Pod's requests/limits for better results. xref: https://tip.golang.org/doc/gc-guide#Memory_limit

**Comment by hiddeco** [comment]
Would advice people who still have this problem to try out helm-controller `>=v0.31.0` which has improvements to the Kubernetes client used by Helm. With these improvements, we have seen a reduction of memory usage of up to ~50% in idle state.

**Comment by stefanprodan** [comment]
Upgrading to Flux 2.1 and enabling Helm index caching should fix this https://fluxcd.io/flux/installation/configuration/vertical-scaling/#enable-helm-repositories-caching
