### ISSUE TITLE
High availability and scaling up

### ISSUE THREAD

**Issue by sambonbonne** [fluxcd/helm-controller#604]
I don't find any clear answer to my question so I hope to find some help here.

We have multiple `HelmRealase` in a cluster and when there is a lot of reconciliation to do, it takes some time because for now we have one Helm Controller and we did not change `--concurrent`.

We want to know how we can "scale" the Helm Controller but we don't know the best way to do it.

We are considering (and are willing to read any other suggestion):

* adding a `--concurrent` flag with more than 4 concurrent releases
* changing the `replicas` fields of the `helm-controller` deployment to more than 1
* maybe a mix of both

We would prefer the second solution, because it would make the Helm Controller less "crashable" but we saw the `--enable-leader-election` and it leads to some other question:

* when this flag is enabled, does it mean that having multiple replicas is useless and only one will reconcile Helm Releases, other replicas waiting in standby (and choosing a new leader in case of crash)?
* what is the expected behavior when having multiple replicas without this flag enabled? Will it possibly create races conditions where multiple Helm Controllers try to reconcile the same Helm Release?

Thanks in advance for any help, advice or answer about any of these questions.

**Comment by adusumillipraveen** [comment]
I think the usual recommended way to scale it up s to have helm controller per namespace and set the flag https://fluxcd.io/flux/components/helm/options/#:~:text=%2D%2Dwatch%2Dall%2Dnamespaces to false.

But it's sometimes very expensive/ pointless to run helm operator in some namespaces which just have 1 or 2 pods running.

It would be great if the controller could support a couple of options like below to easily manage multiple helm controllers.

`--watch-namespaces` list for helm controller to limit which namespaces it should watch
`--ignore-namespaces` list for helm controller to ignore namespaces it should watch

**Comment by kingdonb** [comment]
That is one way to manage scaling Helm Controller, but I don't think that's the recommended way.

See this bootstrap cheatsheet, which covers scaling up source controller, helm controller, and kustomize controller:
https://fluxcd.io/flux/cheatsheets/bootstrap/#increase-the-number-of-workers

The single controller per cluster is the preferred approach for Flux. Horizontally scaling the controller is not really possible because of leader election (without a strategy like setting watch-all-namespaces to false, and partitioning the controllers across namespace, but as mentioned above I think the multiple controllers approach is quite wasteful, comparatively.)

The major limiting factor for Helm reconciling many releases concurrently is probably memory, first and foremost, then requeueing lag. Both of these are addressed in the cheatsheet doc, by raising the limits for CPU and memory, and by setting the `requeue-dependency=` to `5s` (which is `30s` by default). If you have dependency chains with a lot of HelmReleases that depend on each other in sequence, this will be by far the most effective change; those 30s waits add up quite quickly.

**Comment by sambonbonne** [comment]
Thanks for these responses.

I agree that the "one controller per namespace" technique seems a bit resources-intensive (especially for my use case where there is one or two `HelmRelease` per namespace only, but a lot of namespaces).

So if I understand well @kingdonb:

* having multiple controllers with at least 2 `replicas` is not really useful for performance, only for failover?
* "increasing the number of workers" does not really consist on increasing the number of workers but mostly on increasing the amount of work done by the leader controller?

**Comment by kingdonb** [comment]
Since the Flux controllers are a very small image and the process can start quickly, I wouldn't even go so far as to say that having a standby for failover is particularly useful.

The source controller as a replica is especially unhelpful, because the source controller's main job is caching, and so even if you could distribute the load, you'd wind up downloading each artifact again from each source controller over again (or worse, getting 404 for the latest artifact from source controller that legitimately hasn't seen that one yet, so doesn't have a copy for you...) – this type of contention issue is the reason why leader election is done. This problem is unique to source controller, but it should help to be illustrative of the reason why having more than one replica is not always helpful.

The functional "number of workers" is the number set on the `-concurrency` flag, from the link I shared above – the bootstrap cheatsheet guide to scaling has the best advice on the topic. The answer to the question "how many Flux Kustomizations can be reconciled at once" is really governed by this concurrency number, and you don't require more replicas to set it higher.

However, if you find it's impractical to scale it as high as you need to maintain the queue depth as short as you'd like, we'd be happy to take a look at the benchmarks with you and fine tune. It sounds like you have a lot of Flux resources to reconcile in parallel.

This is something that the Flux team can't always test effectively, since those types of clusters cost a lot of money, and it would be great to get an idea how this is really working for you, if you've tried the Flux Monitoring guide, what kind of numbers you actually see once you've adopted the guidance in the linked "cheatsheet" guide.

I know we've been able to scale the Terraform Controller to reconcile many Terraforms at once, but it has a default concurrency of `24` while the Flux controllers mostly have a lower setting. This setting should have some relation to the number of CPU cores/threads that will actually be available on the cluster nodes (Flux which runs on a single node won't be able to reconcile many concurrent threads effectively with a small number of cores, I'd guess... but I'd be guessing, I don't have the benchmarks to say how many is too many)

If this is something which you are hitting the limits of, please don't let me chase you away, we want your feedback about this 😄

**Comment by sambonbonne** [comment]
Thanks again for your very exhaustive explanations!

I don't think we have *that many* HelmReleases compared to what you are abled to test. We will try using the `--concurrent` and `--requeue-dependency` flags, I think it will be really suitable for our use case (at the cost of a higher memory consumption of course, we can afford that).

We were not aware that the "cheatsheet" documentation explained how to scale up (we did not search with the good wording I think) so your pointing at this documentation and your explanations helped us a lot.

Now this is more for my curiosity but why allowing a leader election and multiple replicas if, by design, this does not give a real benefit (even for failover)?

**Comment by kingdonb** [comment]
The leader election from my perspective is a lock, it's not really about "electing a leader" it's about preventing another worker from coming up and butting in.

The design of Kubernetes deployments anticipates the lifecycle of a pod, and orchestrates it over a number of replicas. I think that's all out of Flux's control, once Flux decides to have a single vertical instance of each controller, then the only decision for Flux is whether to be deployments or statefulsets. And I think this leader election is a common pattern in the controller runtime, where Flux's basis for the whole concept of operating on CRDs is founded and derived through.

**Comment by wyndigo-01** [comment]
I'm jumping in here because I have a similar problem and I can't fix it the way I did with helm-operator.

In my use case, I have a single tenant deployment model with roughly 60 charts per tenant, and I will want to support around 50 tenants per cluster.  This will result in around 3000 helm charts that will need to reconciled reasonably quickly.

I was trying to get a model working where all of the platform helm-charts would be in one namespace with a helm controller, and it would deploys those helm-releases to the target namespaces, and then there would be a helm-controller for each namespace so that each helm-controller would only be responsible for about 60 helm-releases.

Unfortunately, I ran into problems when I tried to use --watchallnamespaces=false. I'm guessing the problem was that I was trying to deploy to a different namespace from where the helm-controller and helm-releases were located.

My next thought was trying to restrict which helm-releases each controller could see using RBAC but that is proving tricky because helm-controller appears to need access to a lot of stuff at cluster scope in order to handle reconciliation.

My questions are two fold: is helm-controller expected to be able to handle 3000+ number of helm-releases with enough resources?  Should --watchAllNamespaces=false allow it to process a helm-release in the current namespace that targets another namespace?  Is it supposed to be functionally equivalent to --allow-namespace from helm-operator?

**Comment by wyndigo-01** [comment]
@kingdonb I saw in an above comment that you should be able to set `--watchAllNamespaces` to `false` it should be able to deploy to other namespaces?  Here is the scenario that seemed to not function for me:
helm-controller with `--watchAllNamespaces=false` running in the `helm-releases` namespace. In the helm-releases namespace I had a helm-release with a targetNamespace set to `ServiceX`, and using a source for the chart in the `flux-sources` namespace.

Do you expect that to work?  If so, I can go and try to replicate it again.

**Comment by sambonbonne** [comment]
Thanks @kingdonb for all these clarifications. For me the issue is resolved, as there is new comments I don't close it but feel free to do it if you think it's preferable.

**Comment by stefanprodan** [comment]
For HA deployments see: https://fluxcd.io/flux/installation/configuration/sharding/
