### ISSUE TITLE
CRDs missing in certain scenarios with 0.31.0+

### ISSUE THREAD

**Issue by mjnagel** [fluxcd/helm-controller#655]
In testing the latest Flux release I ran into issues with CRDs not existing for some HelmReleases. 

It appears that installation fails if a controller installed injects custom resource definitions into the cluster which are then later used by a post-install hook. We ran into this issue specifically with OPA Gatekeeper which has the controller create additional CRDs (see the constraint/constraint template doc [here](https://open-policy-agent.github.io/gatekeeper/website/docs/constrainttemplates/)).

This was working in previous versions.

**Comment by hiddeco** [comment]
Thanks for filling the issue @mjnagel.

I spend some time debugging this yesterday, and it happens specifically when a pre-install / pre-upgrade or the upgrade/install procedure itself "magically" injects Custom Resource Definitions.

The cause of this is our move to a persisting Kubernetes client in helm-controller `v0.31.0`, to reduce the (memory) resource usage of the controller (which has been absolutely successful). In combination with the fact that Helm only purges the cache of the discovery client and REST mapper after it runs its own Custom Resource Definition lifecycle (as it can then expect things have changed). This causes things done by e.g. a pre-install hook to not be "seen" by successive steps in the Helm action that's being run.

There are a couple of solutions I can think of that may help solve this problem, listed here based on my personal preference:

1. Try and see if we can get an upstream patch into Helm which purges the discovery client and/or REST mapper cache after running pre-`<action>` and before running post-`<action>` hooks.

    Question is however how much this would have an impact on the resource usage win we were able to get with the introduction of the persistent client, as many cache invalidations will likely be unnecessary, and I deem our chances to contribute something which is triggered through e.g. an annotation on hooks minimal. Specifically because Helm itself at present does not use a persisting client, and it's thus not an issue for the CLI itself.
2. Add a flag to the `HelmRelease` which allows to opt-out of the persistent client for specific releases which are known to cause trouble. This would only increase the resource usage for this specific release, but should otherwise work fine.
3. Revert the change to a persistent client, this is in my opinion not an option as it would double the memory usage of the controller again in many scenarios, while the current configuration works fine for most charts out there.

**Comment by hiddeco** [comment]
For users running into the following (`resource mapping not found`) error:

```
Helm install failed: failed post-install: unable to build kubernetes object for deleting hook gatekeeper/templates/constraints/allowedCapabilities.yaml: resource mapping not found for name: "allowed-capabilities" namespace: "" from "": no matches for kind "K8sPSPCapabilities" in version "constraints.gatekeeper.sh/v1beta1"
ensure CRDs are installed first
```

Try putting an explicit `.spec.persistentClient: false` in your `HelmRelease` resource after updating to helm-controller >=v0.32.0.
