### ISSUE TITLE
Allows delete-override when using subchart

### ISSUE THREAD

**Issue by JordanGoasdoue** [fluxcd/helm-controller#787]
Hello,

I'm just opening this issue to track in case we need to change something else other than the helm version in go.mod

Helm 3.13.0 is out and allows thanks to [this PR](https://github.com/helm/helm/pull/12162)

**Comment by hiddeco** [comment]
We need conformance it actually does not introduce other new issues, as seems to be the case at present given:

- https://github.com/helm/helm/issues/12441
- https://github.com/helm/helm/issues/12450
- https://github.com/helm/helm/issues/12460

In addition, due to the update to Kubernetes 1.28.x this would introduce a new minor. Which means more changes are required throughout the Flux code base, and this will not land before next Flux minor.

**Comment by stefanprodan** [comment]
Helm 3.13 was included in https://github.com/fluxcd/helm-controller/blob/main/CHANGELOG.md#0370
